CREATE TABLE public.access_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  school_id uuid,
  school_name_typed text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT access_requests_pkey PRIMARY KEY (id),
  CONSTRAINT access_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT access_requests_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id)
);
CREATE TABLE public.classroom_members (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  classroom_id uuid NOT NULL,
  student_id uuid NOT NULL,
  role text DEFAULT 'student'::text,
  joined_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT classroom_members_pkey PRIMARY KEY (id),
  CONSTRAINT classroom_members_classroom_id_fkey FOREIGN KEY (classroom_id) REFERENCES public.classrooms(id),
  CONSTRAINT classroom_members_student_id_fkey FOREIGN KEY (student_id) REFERENCES auth.users(id)
);
CREATE TABLE public.classrooms (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  school_id uuid NOT NULL,
  name text NOT NULL,
  invite_code text UNIQUE,
  year integer NOT NULL DEFAULT 2025,
  created_at timestamp with time zone DEFAULT now(),
  teacher_id uuid,
  grade text,
  shift text,
  organization_id uuid,
  CONSTRAINT classrooms_pkey PRIMARY KEY (id),
  CONSTRAINT classrooms_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id),
  CONSTRAINT classrooms_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES auth.users(id),
  CONSTRAINT classrooms_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  permissions jsonb DEFAULT '{"simulations": false, "examCreation": false, "questionBank": false, "studentAdaptation": false, "accessibilityModules": false}'::jsonb,
  CONSTRAINT organizations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text UNIQUE,
  full_name text,
  whatsapp_phone text UNIQUE,
  current_streak integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  plan_tier text DEFAULT 'free'::text,
  role text DEFAULT 'student'::text CHECK (role = ANY (ARRAY['student'::text, 'teacher'::text, 'manager'::text, 'admin'::text, 'secretariat'::text])),
  focus_area text DEFAULT 'geral'::text,
  study_pace text DEFAULT 'moderate'::text,
  days_per_week integer DEFAULT 5,
  hours_per_day integer DEFAULT 2,
  current_question_id uuid,
  whatsapp_jid text,
  onboarding_completed boolean DEFAULT false,
  handshake_completed boolean DEFAULT false,
  asaas_customer_id text,
  subscription_id text,
  subscription_status text DEFAULT 'inactive'::text,
  trial_start_date timestamp with time zone DEFAULT now(),
  cpf text,
  questions_today_count integer DEFAULT 0,
  simulados_today_count integer DEFAULT 0,
  last_reset_date timestamp with time zone DEFAULT now(),
  organization_id uuid,
  school_id uuid,
  classroom_id uuid,
  verification_token text UNIQUE,
  last_active_at timestamp with time zone,
  total_points integer DEFAULT 0,
  last_activity_date date DEFAULT CURRENT_DATE,
  neurodivergence_data jsonb DEFAULT '{}'::jsonb,
  avatar_url text,
  birth_date date,
  target_course character varying,
  target_university character varying,
  school_year character varying,
  accessibility_needs text,
  username text UNIQUE,
  pronouns text,
  bio text,
  learning_style text,
  study_period text,
  whatsapp_opt_in boolean DEFAULT false,
  public_profile boolean DEFAULT false,
  theme_preference text DEFAULT 'system'::text,
  email_notifications boolean DEFAULT true,
  free_hours text,
  onboarding_step text,
  whatsapp_notifications_enabled boolean NOT NULL DEFAULT true,
  conversion_stage text DEFAULT 'nao_abordado'::text,
  session_confirmed_at timestamp with time zone,
  whatsapp_flow text,
  whatsapp_step text,
  whatsapp_temp_data jsonb DEFAULT '{}'::jsonb,
  last_morning_dispatch date,
  last_month_end_seen_ref date,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT profiles_current_question_id_fkey FOREIGN KEY (current_question_id) REFERENCES public.questions(id),
  CONSTRAINT profiles_classroom_id_fkey FOREIGN KEY (classroom_id) REFERENCES public.classrooms(id),
  CONSTRAINT profiles_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT profiles_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id)
);
CREATE TABLE public.schools (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  invite_code text UNIQUE,
  CONSTRAINT schools_pkey PRIMARY KEY (id),
  CONSTRAINT schools_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.security_logs (
  id integer NOT NULL DEFAULT nextval('security_logs_id_seq'::regclass),
  user_id uuid,
  event_type character varying NOT NULL,
  event_description text,
  ip_address inet,
  user_agent text,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT security_logs_pkey PRIMARY KEY (id),
  CONSTRAINT security_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.teacher_classrooms (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  teacher_id uuid NOT NULL,
  classroom_id uuid NOT NULL,
  subject text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  is_owner boolean DEFAULT false,
  CONSTRAINT teacher_classrooms_pkey PRIMARY KEY (id),
  CONSTRAINT teacher_classrooms_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.profiles(id),
  CONSTRAINT teacher_classrooms_classroom_id_fkey FOREIGN KEY (classroom_id) REFERENCES public.classrooms(id)
);
